function highlightStitch(stitchRowNum,whichAxe,imgWidth,color,sz,mg)

margin = mg;
scatter(whichAxe,-margin,stitchRowNum,sz,...
   'marker','>', 'MarkerFaceColor',color,...
    'MarkerEdgeColor',color,'clipping','off');
scatter(whichAxe,imgWidth+margin,stitchRowNum,sz,...
   'marker','<', 'MarkerFaceColor',color,...
    'MarkerEdgeColor',color,'clipping','off');
% plot(whichAxe,[-margin,imgWidth+margin], ...
%     [stitchRowNum,stitchRowNum], ...
%     'LineStyle','--','color','r','clipping','off','marker','none');
end